language: php

matrix:
    include:
        - php: 7.2
          env:
            - COMPOSER_FLAGS=""
        - php: 7.2
          env:
            - COMPOSER_FLAGS="--prefer-lowest --prefer-stable"
        - php: 7.3
          env:
            - COMPOSER_FLAGS=""
        - php: 7.3
          env:
            - COMPOSER_FLAGS="--prefer-lowest --prefer-stable"
        - php: 7.4
          env:
            - COMPOSER_FLAGS=""
            - PHP_CS=true
        - php: 7.4
          env:
            - COMPOSER_FLAGS="--prefer-lowest --prefer-stable"

branches:
    only:
        - master

before_script:
    - composer update --prefer-source --dev $COMPOSER_FLAGS

script:
    - if [[ "$PHP_CS" == "true" ]]; then bin/php-cs-fixer --diff --dry-run -v fix; fi
    - bin/phpspec run -fpretty
