language: php
php:
    - 5.4
    - 5.5
    - 5.6

matrix:
    include:
        - php: 5.4
          env: 'COMPOSER_FLAGS="--prefer-lowest --prefer-stable"'
        - php: 5.5
          env: 'COMPOSER_FLAGS="--prefer-lowest --prefer-stable"'
        - php: 5.6
          env: 'COMPOSER_FLAGS="--prefer-lowest --prefer-stable"'

branches:
    only: [master]

before_script:
    - composer update --prefer-source --dev $COMPOSER_FLAGS

script:
    - bin/php-cs-fixer --diff --dry-run -v fix
    - bin/phpspec run -fpretty
